import type { ContractState, ChargedState } from '@midnight-ntwrk/compact-runtime';

// These types and constants are normally generated by the compactc compiler.
// They are mocked here to allow the frontend to compile before the contract is fully deployed.

export type AgeVerifierPrivateState = {
  birthYear: number;
}

export namespace AgeVerifier {
  export interface Contract<T> {
    proveAge(currentYear: bigint): Promise<void>;
  }
  export interface Witnesses<T> {
    birthYear(context: T): bigint | Promise<bigint>;
  }

  export function ledger(state: ChargedState): any {
    return {
      verificationsCount: 0n // Mocked
    };
  }
}

export const Contract: any = {};
